<x-layouts.app>
    <div class="space-y-6">
        <div class="flex items-center justify-between">
            <div>
                <h1 class="text-2xl font-semibold text-on-surface">{{ $report->title }}</h1>
                <p class="text-sm text-surface-bright mt-1">{{ ucfirst($report->type) }} Report • Generated by {{ $report->created_by?->name ?? 'Unknown' }} on {{ $report->created_at->format('M d, Y H:i') }}</p>
            </div>
            <div class="flex items-center gap-3">
                <a href="{{ route('reports.export', ['report' => $report, 'format' => 'csv']) }}" class="px-4 py-2 bg-success-emerald text-white rounded-lg text-sm font-medium hover:opacity-90 transition-opacity flex items-center gap-2">
                    <span class="material-symbols-outlined text-lg">download</span>
                    Export CSV
                </a>
                <a href="{{ route('reports.index') }}" class="px-4 py-2 bg-surface-container-high text-on-surface rounded-lg hover:opacity-90">Back to Reports</a>
            </div>
        </div>

        @if (session('success'))
            <div class="bg-success-emerald/10 border border-success-emerald/30 rounded-lg p-4 text-success-emerald text-sm">{{ session('success') }}</div>
        @endif

        <div class="grid grid-cols-2 gap-6">
            <div class="bg-surface-container rounded-xl p-4 border border-outline-variant">
                <h2 class="text-lg font-medium text-on-surface mb-4">Report Info</h2>
                <div class="space-y-3">
                    <div class="flex justify-between">
                        <span class="text-sm text-surface-bright">Type</span>
                        <span class="text-sm text-on-surface">{{ ucfirst($report->type) }}</span>
                    </div>
                    <div class="flex justify-between">
                        <span class="text-sm text-surface-bright">Status</span>
                        <span class="px-2 py-1 text-xs rounded-full {{ $report->status === 'generated' ? 'bg-success-emerald/20 text-success-emerald' : 'bg-primary/20 text-primary' }}">
                            {{ ucfirst($report->status) }}
                        </span>
                    </div>
                    @if ($report->parameters)
                        <div class="flex justify-between">
                            <span class="text-sm text-surface-bright">Date Range</span>
                            <span class="text-sm text-on-surface">{{ $report->parameters['date_from'] ?? '-' }} to {{ $report->parameters['date_to'] ?? '-' }}</span>
                        </div>
                    @endif
                    @if ($report->description)
                        <div class="pt-2 border-t border-outline-variant">
                            <span class="text-sm text-surface-bright">Description</span>
                            <p class="text-sm text-on-surface mt-1">{{ $report->description }}</p>
                        </div>
                    @endif
                </div>
            </div>

            <div class="bg-surface-container rounded-xl p-4 border border-outline-variant">
                <h2 class="text-lg font-medium text-on-surface mb-4">Report Data</h2>
                @if ($report->data)
                    <div class="space-y-3">
                        @foreach ($report->data as $key => $value)
                            @if (is_array($value))
                                <div>
                                    <span class="text-sm text-surface-bright">{{ ucfirst(str_replace('_', ' ', $key)) }}</span>
                                    <div class="mt-1 space-y-1">
                                        @foreach ($value as $subKey => $subValue)
                                            <div class="flex justify-between pl-4">
                                                <span class="text-xs text-surface-bright">{{ $subKey }}</span>
                                                <span class="text-xs text-on-surface">{{ $subValue }}</span>
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            @else
                                <div class="flex justify-between">
                                    <span class="text-sm text-surface-bright">{{ ucfirst(str_replace('_', ' ', $key)) }}</span>
                                    <span class="text-sm font-medium text-on-surface">{{ $value }}</span>
                                </div>
                            @endif
                        @endforeach
                    </div>
                @else
                    <p class="text-sm text-surface-bright">No data available.</p>
                @endif
            </div>
        </div>
    </div>
</x-layouts.app>
